name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t python-docker .

      - name: Display Docker image
        run: docker images

      - name: valint install
        id: valint_install
        uses: scribe-security/action-installer@master
        with:
          tools: valint
          
      - name: Scribe BOM Action
        uses: scribe-security/action-bom@master
        with:
          target: 'busybox:latest'
          format: attest-generic
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
          
      - name: Scribe Verify Action
        uses: scribe-security/action-verify@master
        with:
          target: 'busybox:latest'
          format: attest-generic
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
