name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate cyclonedx json SBOM for git repo
        uses: scribe-security/action-bom@master
        with:
          type: git
          target: 'https://github.com/shivam-kush/python-docker-github-actions.git'
          format: json
          force: true
          product-key: python-docker-git-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
      
      - name: Build Docker image
        run: docker build -t python-docker .

      - name: Display Docker image
        run: docker images
          
      - name: Generate cyclonedx json SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: 'python-docker'
          format: json
          force: true
          product-key: python-docker-image-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
          
