name: scribe_github_workflow

on:
  push:
    branches:
      - main

jobs:
  scribe-sign-verify:
    runs-on: ubuntu-latest
    steps:
      
      - name: Scribe BOM Action
        uses: scribe-security/action-bom@master
        with:
          target: 'busybox:latest'
          format: attest-generic
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
          
      - name: Scribe Verify Action
        uses: scribe-security/action-verify@master
        with:
          target: 'busybox:latest'
          format: attest-generic
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
