name: scribe_github_workflow

on:
  push:
    branches:
      - main

jobs:
  scribe-sign-verify:
    runs-on: ubuntu-latest
    steps:
      
      - name: Scribe BOM Action
        uses: scribe-security/action-bom@master
        with:
          target: [target]
          format: [attest, statement, attest-slsa, statement-slsa, attest-generic, statement-generic]
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}
          
      - name: Scribe Verify Action
        uses: scribe-security/action-verify@master
        with:
          target: [target]
          format: [attest, statement, attest-slsa, statement-slsa, attest-generic, statement-generic]
          scribe-enable: true
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: valint verify
        uses: scribe-security/action-verify@master
        with:
          target: 'busybox:latest'
